### ISSUE TITLE
Uh yeah

### ISSUE THREAD

**Issue by EclipsesDev** [Saturn5Vfive/Delta#5]
no documentation on how to use?

(Ignore this dumb comment)

**Comment by joseppiswan** [comment]
kil self

**Comment by quick007** [comment]
*Saturn5Vfive closed this as* **completed**

🤨🤨🤨

**Comment by joseppiswan** [comment]
everything

**Comment by hriiss** [comment]
where is the legendary kil self comment?
(https://media.discordapp.net/attachments/1080528297919774871/1127661493220028476/watermark.gif)

**Comment by ghost** [comment]
kil self

**Comment by marchingblue** [comment]
there is no way actually

**Comment by quick007** [comment]
dudeeee

**Comment by udpcat** [comment]
kil self

**Comment by sudo001** [comment]
kil self

**Comment by zyqunix** [comment]
kil self

**Comment by GuavaDealer** [comment]
absolute cinema (kil self)

**Comment by 0w0v** [comment]
kil self
